language: node_js

jobs:
  include:
    - stage: 'Test'
      name: 'Deploy test site'
      caches:
        - node
      script:
        .travis/deploy_site
    - stage: 'Deploy'
      name: 'Deploy to npmjs'
      caches:
        - node
      script:
        .travis/deploy_lib
      after_succes:
        .travis/push.sh
